using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MCSharp
{
	// Data at http://minecraft.gamepedia.com/Data_Values#Biome_IDs seems inaccurate
	public enum BiomeKind : sbyte
	{
		SunflowerPlains = -127,
		DesertM,
		ExtremeHillsM,
		FlowerForest,
		TaigaM,
		SwamplandM,
		IcePlainsSpikes,
		IceMountainsSpikes,
		JungleM,
		JungleEdgeM,
		BirchForestM,
		BirchForestHillsM,
		RoofedForestM,
		ColdTaigaM,
		MegaSpruceTaiga,
		ExtremeHillsPlusM,
		SavannaM,
		SavannaPlateauM,
		MesaBryce,
		MesaPlateauFM,
		MesaPlateauM,
		Uncalculated = -1,
		Ocean = 0,
		Plains,
		Desert,
		ExtremeHills,
		Forest,
		Taiga,
		Swampland,
		River,
		Nether,
		End,
		FrozenOcean,
		FrozenRiver,
		IcePlains,
		IceMountains,
		MushroomIsland,
		MushroomIslandShore,
		Beach,
		DesertHills,
		ForestHills,
		TaigaHills,
		ExtremeHillsEdge,
		Jungle,
		JungleHills,
		JungleEdge,
		DeepOcean,
		StoneBeach,
		ColdBeach,
		BirchForest,
		BirchForestHills,
		RoofedForest,
		ColdTaiga,
		ColdTaigaHills,
		MegaTaiga,
		MegaTaigaHills,
		ExtremeHillsPlus,
		Savanna,
		SavannaPlateau,
		Mesa,
		MesaPlateauF,
		MesaPlateau,
	}
}
